### ISSUE TITLE
Canvas paint under player

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/mountain_fight#6]
Is it possible to paint under the player or enemies? if i wanted to paint a shadow, for example, under the player. When i paint with gameRef.player!.absoluteCenter.toOffset() it seems to always overlay the player. I was looking for an output similar to Stack. is this possible?

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
Yes, it's possible! Just draw before super.render(canvas) when you do override in render method.
If you want draw other component under other component you can play with priority. This variable (priority) define the order that render all things in the game loop.

**Comment by RafaelBarbosatec** [comment]
Hi Abdurraheem!
Yes, it's possible! Just draw before super.render(canvas) when you do
override in render method.
If you want draw other component under other component you can play with
priority. This variable (priority) define the order that render all things
in the game loop.



Em dom, 24 de jul de 2022 03:17, Abdurraheem Abdulhakeem <
***@***.***> escreveu:
